// auto-generated by circomkit
pragma circom 2.1.2;

include "../partial_decryption_share.circom";

component main {public[C1, encryptedShareC1, encryptedShareC2, xIncrement, partialDecryption]} = PartialDecryptionShare();
